### ISSUE TITLE
Search CI/CD alternatives

### ISSUE THREAD

**Issue by LautaroJayat** [SuperNerdIT/telepathic#3]
## Background
We are in github, but we have no money.

## Tasks
* Get some info on CircleCI, Travis, and other tools that could give us free credits for being open sourced

**Comment by pablogugarcia** [comment]
Why would we initially use the CICD ? for run tests in the PRs ?

**Comment by LautaroJayat** [comment]
As we don't count with any founding at all (for the moment), it would be a good idea to find all free CI/CD tools that we could start using.

Github Actions give us around 2.000 minutes per month without cost: https://github.com/organizations/plan
Circle CI starts with 6.000 minutes per month without cost: https://circleci.com/pricing/
Harness can give us 100 builds per month without cost: https://harness.io/pricing?module=ci#
We could also host some CI/CD solution, but I think this needs to be considered in the future.

The idea would be to decide if we want link this account to these providers, and also choose which kind of event/trigger will be handled by each provider.
For example:

PRs builds/tests could be handled by CircleCI
Merges could be handled by GithubActions
Releases could be handled by Harness

**Comment by LautaroJayat** [comment]
I think, for now, we could start running tests before merging to master.
Then, we could try building afterwards.

When te project starts to get bigger, we could start thinking on automate other kinds of tests, builds, releases, etc.
