### ISSUE TITLE
Define the gitflow we are going to follow

### ISSUE THREAD

**Issue by LautaroJayat** [SuperNerdIT/telepathic#6]
## Background
It would be a great idea if we can choose how are we going to manage our gitflow.

¿Are we going to just use one branch plus tags?
¿Are we going to make some branchs for features and then merge to main when everything goes well?
¿Are we going to commit everything to main?

## Tasks

- [x] Start a discussion and provide the link to it
- [ ] Document the decision inside the `doc` folder

**Comment by pablogugarcia** [comment]
I think since we are only two people, master and feature branch it´s ok.
Why would we initially use the CICD ? for run tests in the PRs ?

**Comment by LautaroJayat** [comment]
I'm fine with that.
Let start with main + feature branches.
